name: dbt CI/CD with Docker Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dbt-tests:
    name: Run dbt Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dbt-core dbt-snowflake

    - name: Set up dbt profile
      env:
        DBT_USER: ${{ secrets.DBT_USER }}
        DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
      run: |
        mkdir -p ~/.dbt
        echo "
            iot_data_project:
              outputs:
                dev:
                  account: xwb98928
                  database: ambient_db
                  password: DBT_PASSWORD
                  role: accountadmin
                  schema: dev
                  threads: 1
                  type: snowflake
                  user: DBT_USER
                  warehouse: compute_wh
              target: dev " > ~/.dbt/profiles.yml

    - name: Run dbt tests
      run: dbt test

  build-and-push:
    name: Build Docker Image and Push to AWS
    runs-on: ubuntu-latest
    needs: dbt-tests # Ensure this job runs only after dbt-tests succeeds

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Tag Docker Image
      run: |
        IMAGE_NAME=${{ secrets.AWS_ECR_REPOSITORY }}
        IMAGE_TAG=latest
        docker build -t $IMAGE_NAME:$IMAGE_TAG .
        docker tag $IMAGE_NAME:$IMAGE_TAG ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/$IMAGE_NAME:$IMAGE_TAG

    - name: Push Docker Image to ECR
      run: |
        IMAGE_NAME=${{ secrets.AWS_ECR_REPOSITORY }}
        IMAGE_TAG=latest
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/$IMAGE_NAME:$IMAGE_TAG
